FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN  npm install
RUN  npm i -g vue
RUN  npm i -g vue-template-compiler 
RUN  npm i -g @vue/cli-service
RUN  npm i -g  @vue/cli-plugin-babel
RUN  npm i -g  @vue/cli-plugin-eslint

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]